name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential pkg-config ffmpeg libcppunit-dev

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                git cmake build-essential pkg-config \
                libtool autoconf automake autopoint gettext gettext-base libgnutls28-dev \
                libssl-dev libdbus-1-dev libexpat1-dev \
                ffmpeg libavutil-dev \
                libudev-dev libpulse-dev libasound2-dev libjack-dev \
                libv4l-dev v4l-utils libdrm-dev \
                libxcb1-dev libx11-dev libxext-dev libxfixes-dev \
                libyaml-cpp-dev yasm nasm libpipewire-0.3-dev libva-dev \
                libvdpau-dev cargo

      - name: Build Jami from source
        run: |
            git config --global http.postBuffer 524288000
            git clone --depth=1 --single-branch --branch master https://review.jami.net/jami-daemon.git
            cd jami-daemon
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/jami-install
            make -j$(nproc)
            sudo make install DESTDIR=${{ github.workspace }}/jami-install

      - name: Configure
        run: |
            cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/jami-install/usr

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Create DEB package
        run: cpack --config build/CPackConfig.cmake -G DEB

      - name: Create Arch package
        run: make arch

      - name: Create source archives
        run: |
          mkdir -p pkg/dist
          tar czf pkg/dist/jamcli-${GITHUB_REF_NAME}.tar.gz --exclude=./.git --exclude=./build .
          7z a pkg/dist/jamcli-${GITHUB_REF_NAME}.7z .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: pkg/dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
